import type { Metadata } from "next";
import "./globals.css";
import { shabname } from "@/libs/font";
import ParallaxProviderCliient from "@/components/providers/PralaxProvider";

export const metadata: Metadata = {
  title: "Hussien Tawhidi",
  description: "Generated by create next app",
};

export default function RootLayProut({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${shabname.variable} antialiased `} dir='rtl'>
        <ParallaxProviderCliient>
          <div className='w-full text-my-light dark:bg-my-white dark:text-my-light bg-my-white '>
            {children}
          </div>
        </ParallaxProviderCliient>
      </body>
    </html>
  );
}
