import type { Metadata } from "next";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import WhatsUpButton from "@/components/shared/WhatsUpButton";

export const metadata: Metadata = {
  title: "Hussien Tawhidi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className='relative bg-my-white'>
    
      <Header />
      <div className='w-full'>
        <div className='fixed bottom-20 z-20 left-1'>
          <WhatsUpButton />
        </div>
        {children}
      </div>
      <Footer />
    </div>
  );
}
