import AdminSidebar from "@/components/dashboard/sidebar/AdminSidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard | Hussien Tawhidi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className='w-full flex'>
     
        <AdminSidebar />
      {children}
    </div>
  );
}
